# Generated by Django 4.2.7 on 2023-11-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('gerant', models.BooleanField(default=None)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'X')], max_length=1)),
            ],
        ),
    ]
