# Generated by Django 4.2.7 on 2023-11-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_alter_user_clientde_alter_user_positif'),
    ]

    operations = [
        migrations.AddField(
            model_name='lieu',
            name='proprietaire',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
