# Generated by Django 4.2.7 on 2023-11-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_reservation_personne_alter_lieu_proprietaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lieu',
            name='provirus',
            field=models.CharField(choices=[('Provirus', 'Provirus'), ('Antivirus', 'Antivirus')], max_length=10),
        ),
    ]
