# Generated by Django 4.2.7 on 2023-11-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_alter_lieu_provirus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='positif',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
