# Generated by Django 4.2.7 on 2023-11-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_alter_user_positif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='positif',
            field=models.BooleanField(null=True),
        ),
    ]
