# Generated by Django 4.2.7 on 2023-11-16 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0008_alter_user_positif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lieu',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.user'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='personne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.user'),
        ),
    ]
